my_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',{'next_page':'/'}),
    url(r'',include('myblog.urls')),
]

my_first_site/my_first_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mypoll/',include('mypoll.urls',namespace="mypoll")),
    url(r'^admin/', include(admin.site.urls)),
]

my_first_site/mypoll/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[url(r'^$',views.IndexView.as_view(),name='index'),
        url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
        url(r'^(?P<pk>[0-9]+)/result/$',views.ResultsView.as_view(),name='result'),
        url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),]

myblog/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns=[url(r'^$',views.post_list,name='post_list'),
             url(r'^post/(?P<pk>[0-9]+)/$',views.post_detail,name="post_detail"),
             url(r'^post/new/$',views.post_new,name="post_new"),
             url(r'^post/(?P<pk>[0-9]+)/edit/$',views.post_edit,name="post_edit"),
             url(r'^drafts',views.post_draft_list,name="post_draft_list"),
             url(r'^post/(?P<pk>[0-9]+)/publish/$',views.post_publish, name="post_publish"),
             url(r'^post/(?P<pk>[0-9]+)/remove/$',views.post_remove, name="post_remove"),
        ]

my_first_site/mypoll/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Date Published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        #return self.pub_date>=timezone.now()-datetime.timedelta(days=1)
        now=timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date<=now 
    was_published_recently.admin_order_field='pub_date'
    was_published_recently.boolean=True
    was_published_recently.short_description="Published Recently"

class Choice(models.Model):
    question=models.ForeignKey(Question)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

myblog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

#The first model we will create is a post model

class Post(models.Model):
    author=models.ForeignKey('auth.User')
    title=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def __unicode__(self):
        return self.title

myblog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','text',)

my_first_site/mypoll/views.py
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.views import generic
from .models import Question,Choice
from django.core.urlresolvers import reverse
from django.shortcuts import render,get_object_or_404
from django.utils import timezone
#from django.template import RequestContext,loader
# Create your views here.

#def index(request):
#    return HttpResponse("Hello World you are at the polls index")
#def index(request):
#    latest_question_list=Question.objects.order_by('-pub_date')[:5]
#    template=loader.get_template('mypoll/index.html')
#    context=RequestContext(request,{'latest_question_list':latest_question_list,})
#    return HttpResponse(template.render(context))

#def index(request):
#    latest_question_list=Question.objects.order_by('-pub_date')[:5]
#    context={'latest_question_list':latest_question_list}
#    return render(request,'mypoll/index.html',context)

#detail =lambda request,question_id : HttpResponse("You are looking at question %s" % question_id) 

#def detail(request,question_id):
#    try:
#        question=Question.objects.get(pk=question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist")
#    return render(request,'mypoll/details.html',{'question':question})

#def detail(request,question_id):
#    question=get_object_or_404(Question,pk=question_id)
#    return render(request,'mypoll/details.html',{'question':question})


#results=lambda request,question_id :HttpResponse("You are looking at the results of question %s" % question_id)

#vote=lambda request,question_id:HttpResponse("You are voting on question %s" % question_id) 

#Final version of vote view 
def vote(request,question_id):
    p=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=p.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'mypoll/details.html',{'question':p,'error_message':"you didn't select a choice",})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('mypoll:result',args=(p.id,)))

#Final version of results view
#def result(request,question_id):
#    question=get_object_or_404(Question,pk=question_id)
#    return render(request,'mypoll/results.html',{'question':question})
#We will implement the generic views built into Django

class IndexView(generic.ListView):
    template_name='mypoll/index.html'
    context_object_name='latest_question_list'

    #get_queryset=lambda self : Question.objects.order_by('-pub_date')[:5]
    #This will return the last five published questions,this does not include future questions
    get_queryset=lambda self:Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model=Question
    template_name='mypoll/details.html'

    get_queryset =lambda self:Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model=Question
    template_name='mypoll/results.html'

myblog/views.py
from django.shortcuts import render,get_object_or_404
from django.utils import timezone
from .forms import PostForm
from .models import Post
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
#post_list=lambda request: render(request,'myblog/post_list.html',{}
def post_list(request):
    posts=Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request,'myblog/post_list.html',{'posts':posts})

def post_detail(request,pk):
    post=get_object_or_404(Post,pk=pk)
    return render(request,'myblog/post_detail.html',{'post':post})

@login_required
def post_new(request):
    if request.method=="POST":
        form=PostForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.published_date=timezone.now()
            post.save()
            return redirect('myblog.views.post_detail',pk=post.pk)
    else:
        form=PostForm()
    return render(request,'myblog/post_edit.html',{"form":form})

@login_required
def post_edit(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=="POST":
        form=PostForm(request.POST,instance=post)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.published_date=timezone.now()
            post.save()
            return redirect('myblog.views.post_detail',pk=post.pk)
    else:
        form=PostForm(instance=post)
    return render(request,'myblog/post_edit.html',{"form":form})

@login_required
def post_draft_list(request):
    posts=Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request,'myblog/post_draft_list.html',{'posts':posts})

@login_required
def post_publish(request,pk):
    post=get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('myblog.views.post_detail',pk=pk)

@login_required
def post_remove(request,pk):
    post=get_object_or_404(Post,pk=pk)
    post.delete()
    return redirect('myblog.views.post_list')

my_first_site/mypoll/templates/mypoll/details.html
<!--<h1>{{question.question_text}}</h1>

<ul>

{% for choice in question.choice.set.all%}
<li>{{choice.choice_text }}</li>
{% endfor %}

</ul>

--!>

<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'mypoll:vote' question.id %}" method="post">
	{% csrf_token%}
	{% for choice in question.choice_set.all%}
	<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
	<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
	{% endfor %}

	<input type="submit" value="Vote" />



</form>

my_first_site/mypoll/templates/mypoll/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'mypoll/style.css'%}" />
{% if latest_question_list%}
   <ul>
	   {% for question in latest_question_list%}
	   <li><a href='{% url 'mypoll:detail' question.id%}'>{{question.question_text}}</a></li>
	   {%endfor%}
   </ul>
	   {%else%}
	   <p>No polls are available</p>
{% endif%}

my_first_site/mypoll/templates/mypoll/results.html
<h1>{{question.question_text}} </h1>

<ul>
	{% for choice in question.choice_set.all%}
	<li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
	{%endfor%}
</ul>

<a href="{% url 'mypoll:detail' question.id%}">Vote again?</a>

myblog/templates/myblog/base.html
{% load staticfiles %}
<html>
	<head>
		<title>Michael's Blog</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{%static "css/myblog.css" %}">
	    <link	href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"	rel="stylesheet"	type="text/css">


	</head>
	<body>
		<div class="page-header">
			{% if user.is_authenticated %}
			<a href="{% url "post_new"%}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
			<a href="{% url "post_draft_list" %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
			<p class="top-menu">Hello {{user.username }}<small>(<a href="{% url "django.contrib.auth.views.logout"%}">Log out</a>)</small></p>
			{% else %}
			<a href="{% url "django.contrib.auth.views.login" %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
			{% endif %}
			<h1><a href="{% url "myblog.views.post_list" %}">Michael's Blog</a></h1>
		</div>	

		<div class="content container">
			<div class="row">
				<div class="col-md-8">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

myblog/templates/myblog/post_detail.html
{% extends "myblog/base.html"%}

{%block content %}

	<div class="post">
		{% if post.published_date %}
		<div class="date">
			{{post.published_date }}
		</div>
		{% else %}
		<a class="btn btn-default" href="{% url "myblog.views.post_publish" pk=post.pk%}">Publish</a>
		{% endif %}
		{% if user.is_authenticated %}
		<a class="btn btn-default" href="{% url "post_edit" pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		<a class="btn btn-default" href="{% url "post_remove" pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
		{% else %}
		<a href="{% url "django.contrib.auth.views.login" %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
		{% endif %}
		<h1>{{ post.title }}</h1>
		<p>{{post.text|linebreaks }}</p>
	</div>
{% endblock %}

myblog/templates/myblog/post_draft_list.html
{% extends "myblog/base.html"%}

{% block content%}
	{% for post in posts%}
	<div class="post">
		<p class="date">created: {{post.created_date|date:"d-m-y"}} </p>
		<h1><a href="{% url "myblog.views.post_detail" pk=post.pk %}">{{post.title}}</a></h1>
		<p>{{post.text|truncatechars:200 }} </p>
	</div>
	{%endfor%}
{%endblock%}

myblog/templates/myblog/post_edit.html
{% extends "myblog/base.html" %}

{% block content %}
	<h1>New Post</h1>
	<form method="POST" class="post-form"> {% csrf_token %}
		{{form.as_p}}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock%}

myblog/templates/myblog/post_list.html
{% extends "myblog/base.html" %}
{% block content %}
		{% for post in posts%}

		<div class="post">
			<div class="date">
			<p>published {{post.published_date}}</p>
		</div>
		<h1><a href="{% url "post_detail" pk=post.pk %}">{{post.title}}</a></h1>
			<p>{{post.text|linebreaks }}</p>
		</div>
		{% endfor %}
{% endblock content %}